InterPro_ID: null
KEGG_ID:
- K21104
alignment_method: upimapi
concat_models: true
consensus: false
database: UniProt
expansion: false
hmm_database_name: KEGG_21104
hmm_validation: true
hmmsearch_out_type: tsv
input_file: null
input_file_db_const: null
input_type: protein
metagenomic: false
msa_aligner: tcoffee
out_table_format: tsv
output_directory: MPARTY_results
overwrite: false
seqids: []
threads: 12
thresholds: false
verbose: true
workflow: database_construction
