InterPro_ID: null
KEGG_ID: null
alignment_method: upimapi
concat_models: true
consensus: false
database: UniProt
expansion: false
hmm_database_name: PBAT_manual
hmm_validation: false
hmmsearch_out_type: tsv
input_file: Aspergillus_5052.fasta
input_file_db_const: null
input_type: protein
metagenomic: false
msa_aligner: tcoffee
out_table_format: excel
output_directory: Aspergillus_out_manual
overwrite: false
seqids: too_big
threads: 12
thresholds: false
verbose: true
workflow: annotation
