60-65:
- '2'
75-80:
- '1'
80-85:
- '1'
alignment_method: diamond
concat_models: true
database: swissprot
hmm_database_name: PET
hmmsearch_out_type: tsv
input_file: null
input_file_db_const: ci/sequences_PET.fasta
input_type: protein
metagenomic: false
msa_aligner: tcoffee
out_table_format: excel
output_directory: MPARTY_results
overwrite: false
seqids: []
threads: 8
thresholds:
- 60-65
- 75-80
- 80-85
validation: true
verbose: true
workflow: database_construction
