database: UniProt
hmm_database_name: PE
hmmsearch_out_type: tsv
input_file: sequences.fasta
input_file_db_const: null
input_type: protein
metagenomic: false
out_table_format: excel
output_directory: output_results
seqids:
- A0A1H6AD45
- G9BY57
- O22443
- Q02567
- Q9HTK9
threads: 1
thresholds:
- 60-65
- 65-70
- 70-75
- 75-80
- 80-85
- 85-90
validation: false
workflow: annotation
