name: mparty
channels:
  - conda-forge
  - bioconda
dependencies:
  - upimapi
  - pyyaml
  - hmmer
  - t-coffee
  - cd-hit
  - pandas
  - openpyxl
  - snakemake
  - clint
  - blast
  - diamond
  - muscle
  - beautifulsoup4
  - kma